const SET_HOUSE_TYPE = "SET_HOUSE_TYPE";
const SET_HOUSE_STATE = "SET_HOUSE_STATE";
const SET_NUMBER_OF_BEDROOMS = "SET_NUMBER_OF_BEDROOMS";
const SET_NUMBER_OF_BATHROOMS = "SET_NUMBER_OF_BATHROOMS";
const SET_PRICE_RANGE = "SET_PRICE_RANGE";
const SET_PUBLICATION_DATE = "SET_PUBLICATION_DATE";
const SET_EQUIPMENT = "SET_EQUIPMENT";
const GET_FILTERED_PROPERTIES = "GET_FILTERED_PROPERTIES";
const LOADING_PROPERTIES = "LOADING_PROPERTIES";

export {
  SET_HOUSE_TYPE,
  SET_HOUSE_STATE,
  SET_NUMBER_OF_BEDROOMS,
  SET_NUMBER_OF_BATHROOMS,
  SET_PRICE_RANGE,
  SET_PUBLICATION_DATE,
  SET_EQUIPMENT,
  GET_FILTERED_PROPERTIES,
  LOADING_PROPERTIES
};
