export const SET_HOUSE_TYPE = "SET_HOUSE_TYPE";
export const SET_HOUSE_STATE = "SET_HOUSE_STATE";
export const SET_NUMBER_OF_BEDROOMS = "SET_NUMBER_OF_BEDROOMS";
export const SET_NUMBER_OF_BATHROOMS = "SET_NUMBER_OF_BATHROOMS";
export const SET_PRICE_RANGE = "SET_PRICE_RANGE";
export const SET_PUBLICATION_DATE = "SET_PUBLICATION_DATE";
export const SET_EQUIPMENT = "SET_EQUIPMENT";
export const GET_FILTERED_PROPERTIES = "GET_FILTERED_PROPERTIES";
export const LOADING_PROPERTIES = "LOADING_PROPERTIES";

export const GET_PROPIERTIES = "GET_PROPIERTIES";
export const FAV_USER_PROPIERTIES = "FAV_USER_PROPIERTIES";
export const FILTER_PROPIERTIES = "FILTER_PROPIERTIES";
export const CITY_PROPIERTIES = "CITY_PROPIERTIES";
export const RESET_PROPIERTIES = "RESET_PROPIERTIES";
export const SET_FILTERS = 'SET_FILTERS';
