export const SET_RADIO_FILTERS = 'SET_RADIO_FILTERS';
export const SET_CHECKBOX_FILTERS = 'SET_CHECKBOX_FILTERS';
export const SET_SELECT_FILTERS = 'SET_SELECT_FILTERS';
export const SET_RANGE_FILTERS = 'SET_RANGE_FILTERS';
export const SET_MORE_FILTERS = 'SET_MORE_FILTERS';
export const SET_SEARCH_FILTERS = 'SET_SEARCH_FILTERS';
export const LOAD_FILTERS = 'LOAD_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
